---
title: "Awesome"
date: 2019-04-10
---
author: Tenrax
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is awesome

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
